steps:
# This step will build and push new container image to Google Container Registry(GCR)
- name: "gcr.io/cloud-builders/gsutil"    
  args: ["cp", "gs://devops-secrets/env.txt", ".env"] 

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/devops', '.']
 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/devops']

# This step will deploy the new container image to cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run','deploy', 'devops', '--image=gcr.io/$PROJECT_ID/devops', '--region=us-central1', '--allow-unauthenticated']
